variables:
  - name: TARGET_REPO
    default: oci://ghcr.io/justin-o12/packages/uds

  - name: VERSION
    description: "The version of the packages to build"
    # x-release-please-start-version
    default: "0.2.4"
    # x-release-please-end

tasks:
  - name: package
    description: "Build and publish the UDS package"
    actions:
      - description: "Create the ARC Zarf Package"
        cmd: |
          set -e
          ZARF_ARCHITECTURE=amd64 uds run -f tasks/create.yaml arc-package --no-progress
          ZARF_ARCHITECTURE=arm64 uds run -f tasks/create.yaml arc-package --no-progress

      - description: "Publish the packages"
        cmd: |
          set -e
          uds zarf package publish zarf-package-actions-runner-controller-amd64-${VERSION}.tar.zst ${TARGET_REPO}
          uds zarf package publish zarf-package-actions-runner-controller-arm64-${VERSION}.tar.zst ${TARGET_REPO}
